repositories:
  - name: nginx-stable
    url: https://helm.nginx.com/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnam

releases:
  - name: ingress
    chart: nginx-stable/nginx-ingress
    wait: true
  - name: spark
    namespace: poc
    createNamespace: true
    chart: bitnami/spark
    values:
      - ingress.enabled: true
        image.tag: 3.1.3-debian-11-r6
    wait: true
  - name: local-lambda
    namespace: poc
    chart: lambdas/local-deploy
    wait: true
  - name: spark-submit
    namespace: poc
    installed: true
    chart: pipelines/pipelines


