/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ai.triton.platform.app

import org.apache.commons.text.WordUtils


import org.apache.beam.sdk.options.Default
import org.apache.beam.sdk.options.Description
import org.apache.beam.sdk.options.PipelineOptions
import org.apache.beam.sdk.options.PipelineOptionsFactory

fun main() {
    
}
