/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.triton.platform.kotlin-library-conventions")
}

dependencies {
    implementation(project(":utilities"))
    implementation("com.amazonaws:aws-java-sdk-lambda")
    implementation("org.apache.beam:beam-sdks-java-core")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2")
}