/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ai.triton.platform.kotlin-library-conventions")
}

dependencies {
    implementation("org.apache.beam:beam-sdks-java-core")
}