/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ai.triton.platform

import ai.triton.platform.pipeline.PocPipeline
import org.apache.beam.sdk.io.FileSystems
import org.apache.beam.sdk.options.PipelineOptionsFactory
import org.apache.beam.sdk.testing.TestPipeline


fun main(args: Array<String>) {
    val options = PipelineOptionsFactory.fromArgs(*args).create()
    val pipeline = PocPipeline(options)
    pipeline.run().waitUntilFinish()
}
